"""Data models for sa-openapi."""

from .channel import (
    CampaignDetail,
    CampaignListResponse,
    ChannelLinkDetail,
    ChannelLinkListResponse,
)
from .common import (
    BookmarkData,
    ErrorInfo,
    HttpApiResult,
    Pagination,
    QueryResult,
)
from .dashboard import Bookmark, Navigation
from .dataset import CreateSavedQueryParams, Dataset, SavedQuery
from .model import (
    ApiFunnelDefine,
    ApiRequestElementCondition,
    ApiRequestEventWithFilter,
    ApiRequestFilter,
    ApiRequestMeasure,
    AttributionReport,
    AttributionReportRequest,
    AttributionReportResponse,
    FunnelReport,
    FunnelReportRequest,
    FunnelReportResponse,
    LinkEvent,
    Measure,
    RetentionReport,
    RetentionReportRequest,
    RetentionReportResponse,
    SqlExplainResult,
    SqlQueryRequest,
    SqlQueryResponse,
    SqlValidateResult,
)

__all__ = [
    "ApiFunnelDefine",
    "ApiRequestElementCondition",
    "ApiRequestEventWithFilter",
    "ApiRequestFilter",
    "ApiRequestMeasure",
    "AttributionReport",
    "AttributionReportRequest",
    "AttributionReportResponse",
    "Bookmark",
    "BookmarkData",
    "CampaignDetail",
    "CampaignListResponse",
    "ChannelLinkDetail",
    "ChannelLinkListResponse",
    "CreateSavedQueryParams",
    "Dataset",
    "ErrorInfo",
    "FunnelReport",
    "FunnelReportRequest",
    "FunnelReportResponse",
    "HttpApiResult",
    "LinkEvent",
    "Measure",
    "Navigation",
    "Pagination",
    "QueryResult",
    "RetentionReport",
    "RetentionReportRequest",
    "RetentionReportResponse",
    "SavedQuery",
    "SqlExplainResult",
    "SqlQueryRequest",
    "SqlQueryResponse",
    "SqlValidateResult",
]
